let a = 10;
console.log(typeof a);
let b = "shweta";
console.log(typeof b);
let c = 10.5;
console.log(typeof c);
let d = NaN;
console.log(typeof d);
let e = null;
console.log(typeof e);
let f = [1, 2, 3, 4, 5];
console.log(typeof f);
let g = true;
console.log(typeof g);
let h = undefined;
console.log(typeof h);
let i = 10 + 10;
console.log(typeof i);
console.log(typeof 10 + 10);
console.log(typeof {});
console.log(typeof typeof 10);
console.log(typeof NaN);
